#pragma once
#include <analogInputs/analogV1.h>
#include <analogInputs/analogV2.h>
#include <analogInputs/analogV3.h>
#include <analogInputs/analogV4.h>
#include <analogInputs/analogR1.h>
#include <analogInputs/analogR2.h>
#include <analogInputs/analogR3.h>
#include <analogInputs/analogR4.h>
#include <analogInputs/analogKR1.h>
#include <analogInputs/fuelLevel.h>